/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.scilab.modules.xcos;

public enum ObjectProperties {
    PARENT_DIAGRAM,
    GEOMETRY,
    DESCRIPTION,
    RELATED_TO,
    INTERFACE_FUNCTION,
    SIM_FUNCTION_NAME,
    SIM_FUNCTION_API,
    SIM_SCHEDULE,
    ANGLE,
    EXPRS,
    INPUTS,
    OUTPUTS,
    EVENT_INPUTS,
    EVENT_OUTPUTS,
    PARENT_BLOCK,
    CHILDREN,
    PORT_REFERENCE,
    STYLE,
    LABEL,
    DESTINATION_PORT,
    SOURCE_PORT,
    CONTROL_POINTS,
    DATATYPE,
    DATATYPE_ROWS,
    DATATYPE_COLS,
    DATATYPE_TYPE,
    SOURCE_BLOCK,
    PORT_KIND,
    IMPLICIT,
    PORT_NUMBER,
    CONNECTED_SIGNALS;
}

