/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.scilab.modules.xcos;

public enum ObjectProperties {
    PARENT_DIAGRAM,     //!< model::Annotation::parentDiagram or model::Block::parentDiagram or model::Link::parentDiagram value
    GEOMETRY,           //!< model::Annotation::geometry or model::Block::geometry value
    DESCRIPTION,        //!< model::Annotation::description
    RELATED_TO,         //!< model::Annotation::relatedTo
    INTERFACE_FUNCTION, //!< model::Block::interfaceFunction value
    SIM_FUNCTION_NAME,  //!< model::Descriptor::functionName value (stored into model::Block::sim)
    SIM_FUNCTION_API,   //!< model::Descriptor::functionApi value (stored into model::Block::sim)
    SIM_SCHEDULE,       //!< model::Descriptor::schedulingProperties value (stored into model::Block::sim)
    SIM_BLOCKTYPE,      //!< model::Descriptor::blocktype value (stored into model::Block::sim)
    SIM_DEP_UT,         //!< model::Descriptor::dep_ut value (stored into model::Block::sim)
    ANGLE,              //!< model::Block::flip and theta values
    EXPRS,              //!< model::Block::exprs value
    INPUTS,             //!< model::Block::in value
    OUTPUTS,            //!< model::Block::out value
    EVENT_INPUTS,       //!< model::Block::ein value
    EVENT_OUTPUTS,      //!< model::Block::eout value
    STATE,              //!< model::Block::state value
    DSTATE,             //!< model::Block::dstate value
    ODSTATE,            //!< model::Block::odstate value
    NZCROSS,            //!< model::Block::nzcross value
    NMODE,              //!< model::Block::nmode value
    RPAR,               //!< model::Block::rpar value
    IPAR,               //!< model::Block::ipar value
    OPAR,               //!< model::Block::opar value
    EQUATIONS,          //!< model::Block::equations value
    UID,                //!< model::Block::uid value
    PARENT_BLOCK,       //!< model::Block::parentBlock value
    CHILDREN,           //!< model::Block::children for superblocks or model::Diagram::children value
    PORT_REFERENCE,     //!< model::Block::portReference value
    STYLE,              //!< model::Block & Port::style value
    LABEL,              //!< model::Block & Port & Link::label or id value
    DESTINATION_PORT,   //!< model::Link::destinationPort value
    SOURCE_PORT,        //!< model::Link::sourcePort value
    CONTROL_POINTS,     //!< model::Link::controlPoints value
    THICK,              //!< model::Link::thick value
    COLOR,              //!< model::Link::color value
    KIND,               //!< model::Link::kind value
    FROM,               //!< model::Link::from value
    TO,                 //!< model::Link::to value
    DATATYPE,           //!< model::Port::dataType value
    DATATYPE_ROWS,      //!< model::Port::dataType adapter helper
    DATATYPE_COLS,      //!< model::Port::dataType adapter helper
    DATATYPE_TYPE,      //!< model::Port::dataType adapter helper
    FIRING,             //!< model::Port::firing value
    SOURCE_BLOCK,       //!< model::Port::sourceBlock value
    PORT_KIND,          //!< model::Port::kind value
    IMPLICIT,           //!< model::Port::implicit value
    PORT_NUMBER,        //!< model::Port::portNumber value
    CONNECTED_SIGNALS,  //!< model::Port::connectedSignals value
}

