['Build full linear system  pendulum-observer-compensator'
	   ' '
	   ' ft=[f-g*kr            -g*kr'
	   '     0*f               f-k*h]'
	   ' '
	   ' gt=[g;0*g];'
	   ' ht=[h,0*h];'
	   ''
	   ' pr=syslin(''c'',ft,gt,ht);'
	   ''
	   '//Check the closed loop dynamic'
	   ' spec(pr.A)'
	   ' '
	   '//transfer matrix representation'
	   ' hr=clean(ss2tf(pr),1.d-10)'
	   ' '
	   '//frequency analysis'
	   ' black(pr,0.01,100,[''position'',''theta''])'
	   ' g_margin(pr(1,1))']
