/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.scilab.modules.graphic_objects;

public class DataLoader {
  public static int getDataSize(String id) {
    return DataLoaderJNI.getDataSize(id);
  }

  public static void fillVertices(String id, java.nio.FloatBuffer buffer, int bufferLength, int elementsSize, int coordinateMask, double[] scale, double[] translation) {
    assert buffer.isDirect() : "Buffer must be allocated direct.";
    {
      DataLoaderJNI.fillVertices(id, buffer, bufferLength, elementsSize, coordinateMask, scale, translation);
    }
  }

  public static void fillColors(String id, java.nio.FloatBuffer buffer, int bufferLength, int elementsSize) {
    assert buffer.isDirect() : "Buffer must be allocated direct.";
    {
      DataLoaderJNI.fillColors(id, buffer, bufferLength, elementsSize);
    }
  }

  public static int getIndicesSize(String id) {
    return DataLoaderJNI.getIndicesSize(id);
  }

  public static void fillIndices(String id, java.nio.IntBuffer buffer, int bufferLength) {
    assert buffer.isDirect() : "Buffer must be allocated direct.";
    {
      DataLoaderJNI.fillIndices(id, buffer, bufferLength);
    }
  }

  public static int getWireIndicesSize(String id) {
    return DataLoaderJNI.getWireIndicesSize(id);
  }

  public static void fillWireIndices(String id, java.nio.IntBuffer buffer, int bufferLength) {
    assert buffer.isDirect() : "Buffer must be allocated direct.";
    {
      DataLoaderJNI.fillWireIndices(id, buffer, bufferLength);
    }
  }

}
