/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.scilab.modules.graphic_objects;

public class NativeGL {
  public static void loadGLData(java.nio.DoubleBuffer BUFF, String id) {
    assert BUFF.isDirect() : "Buffer must be allocated direct.";
    {
      NativeGLJNI.loadGLData(BUFF, id);
    }
  }

  public static void updateObject(String id) {
    NativeGLJNI.updateObject(id);
  }

}
