//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.11 at 11:37:04 AM CEST 
//


package org.scilab.modules.xcos.simulink.patterns;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Int2StrParameter complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Int2StrParameter">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="parMap" type="{}Int2StrValueMap" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="sim" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="xCos" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="dsc" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Int2StrParameter", propOrder = {
    "parMap"
})
public class Int2StrParameter {

    @XmlElement(required = true)
    protected List<Int2StrValueMap> parMap;
    @XmlAttribute(required = true)
    protected String sim;
    @XmlAttribute(required = true)
    protected String xCos;
    @XmlAttribute
    protected String dsc;

    /**
     * Gets the value of the parMap property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the parMap property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParMap().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Int2StrValueMap }
     * 
     * 
     */
    public List<Int2StrValueMap> getParMap() {
        if (parMap == null) {
            parMap = new ArrayList<Int2StrValueMap>();
        }
        return this.parMap;
    }

    /**
     * Gets the value of the sim property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSim() {
        return sim;
    }

    /**
     * Sets the value of the sim property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSim(String value) {
        this.sim = value;
    }

    /**
     * Gets the value of the xCos property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXCos() {
        return xCos;
    }

    /**
     * Sets the value of the xCos property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXCos(String value) {
        this.xCos = value;
    }

    /**
     * Gets the value of the dsc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDsc() {
        return dsc;
    }

    /**
     * Sets the value of the dsc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDsc(String value) {
        this.dsc = value;
    }

}
