//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.11 at 11:37:04 AM CEST 
//


package org.scilab.modules.xcos.simulink.patterns;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.scilab.modules.xcos.simulink.patterns package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Blocks_QNAME = new QName("", "blocks");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.scilab.modules.xcos.simulink.patterns
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Int2StrValueMap }
     * 
     */
    public Int2StrValueMap createInt2StrValueMap() {
        return new Int2StrValueMap();
    }

    /**
     * Create an instance of {@link Str2IntValueMap }
     * 
     */
    public Str2IntValueMap createStr2IntValueMap() {
        return new Str2IntValueMap();
    }

    /**
     * Create an instance of {@link Int2StrParameter }
     * 
     */
    public Int2StrParameter createInt2StrParameter() {
        return new Int2StrParameter();
    }

    /**
     * Create an instance of {@link Str2IntParameter }
     * 
     */
    public Str2IntParameter createStr2IntParameter() {
        return new Str2IntParameter();
    }

    /**
     * Create an instance of {@link StringParameter }
     * 
     */
    public StringParameter createStringParameter() {
        return new StringParameter();
    }

    /**
     * Create an instance of {@link IntegerValueMap }
     * 
     */
    public IntegerValueMap createIntegerValueMap() {
        return new IntegerValueMap();
    }

    /**
     * Create an instance of {@link StringValueMap }
     * 
     */
    public StringValueMap createStringValueMap() {
        return new StringValueMap();
    }

    /**
     * Create an instance of {@link IntegerParameter }
     * 
     */
    public IntegerParameter createIntegerParameter() {
        return new IntegerParameter();
    }

    /**
     * Create an instance of {@link BlockPallete }
     * 
     */
    public BlockPallete createBlockPallete() {
        return new BlockPallete();
    }

    /**
     * Create an instance of {@link GeneralParameters }
     * 
     */
    public GeneralParameters createGeneralParameters() {
        return new GeneralParameters();
    }

    /**
     * Create an instance of {@link Block }
     * 
     */
    public Block createBlock() {
        return new Block();
    }

    /**
     * Create an instance of {@link SimpleParameter }
     * 
     */
    public SimpleParameter createSimpleParameter() {
        return new SimpleParameter();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BlockPallete }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "blocks")
    public JAXBElement<BlockPallete> createBlocks(BlockPallete value) {
        return new JAXBElement<BlockPallete>(_Blocks_QNAME, BlockPallete.class, null, value);
    }

}
