/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.scilab.modules.graphic_objects.JoGLView.nativegl;

public class NativeGL {
    private static boolean loaded = false;

    public static void loadGLData(String id) {
        loadLib();
        NativeGLJNI.loadGLData(id);
    }

    public static void updateObject(String id) {
        loadLib();
        NativeGLJNI.updateObject(id);
    }

    private static void loadLib() {
        if (!loaded) {
            System.loadLibrary("scigraphic_objects");
            loaded = true;
        }
    }
}
