/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */
/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif


/* -----------------------------------------------------------------------------
 * swigrun.swg
 *
 * This file contains generic C API SWIG runtime support for pointer
 * type checking.
 * ----------------------------------------------------------------------------- */

/* This should only be incremented when either the layout of swig_type_info changes,
   or for whatever reason, the runtime changes incompatibly */
#define SWIG_RUNTIME_VERSION "4"

/* define SWIG_TYPE_TABLE_NAME as "SWIG_TYPE_TABLE" */
#ifdef SWIG_TYPE_TABLE
# define SWIG_QUOTE_STRING(x) #x
# define SWIG_EXPAND_AND_QUOTE_STRING(x) SWIG_QUOTE_STRING(x)
# define SWIG_TYPE_TABLE_NAME SWIG_EXPAND_AND_QUOTE_STRING(SWIG_TYPE_TABLE)
#else
# define SWIG_TYPE_TABLE_NAME
#endif

/*
  You can use the SWIGRUNTIME and SWIGRUNTIMEINLINE macros for
  creating a static or dynamic library from the SWIG runtime code.
  In 99.9% of the cases, SWIG just needs to declare them as 'static'.

  But only do this if strictly necessary, ie, if you have problems
  with your compiler or suchlike.
*/

#ifndef SWIGRUNTIME
# define SWIGRUNTIME SWIGINTERN
#endif

#ifndef SWIGRUNTIMEINLINE
# define SWIGRUNTIMEINLINE SWIGRUNTIME SWIGINLINE
#endif

/*  Generic buffer size */
#ifndef SWIG_BUFFER_SIZE
# define SWIG_BUFFER_SIZE 1024
#endif

/* Flags for pointer conversions */
#define SWIG_POINTER_DISOWN        0x1
#define SWIG_CAST_NEW_MEMORY       0x2

/* Flags for new pointer objects */
#define SWIG_POINTER_OWN           0x1


/*
   Flags/methods for returning states.

   The SWIG conversion methods, as ConvertPtr, return an integer
   that tells if the conversion was successful or not. And if not,
   an error code can be returned (see swigerrors.swg for the codes).

   Use the following macros/flags to set or process the returning
   states.

   In old versions of SWIG, code such as the following was usually written:

     if (SWIG_ConvertPtr(obj,vptr,ty.flags) != -1) {
       // success code
     } else {
       //fail code
     }

   Now you can be more explicit:

    int res = SWIG_ConvertPtr(obj,vptr,ty.flags);
    if (SWIG_IsOK(res)) {
      // success code
    } else {
      // fail code
    }

   which is the same really, but now you can also do

    Type *ptr;
    int res = SWIG_ConvertPtr(obj,(void **)(&ptr),ty.flags);
    if (SWIG_IsOK(res)) {
      // success code
      if (SWIG_IsNewObj(res) {
        ...
	delete *ptr;
      } else {
        ...
      }
    } else {
      // fail code
    }

   I.e., now SWIG_ConvertPtr can return new objects and you can
   identify the case and take care of the deallocation. Of course that
   also requires SWIG_ConvertPtr to return new result values, such as

      int SWIG_ConvertPtr(obj, ptr,...) {
        if (<obj is ok>) {
          if (<need new object>) {
            *ptr = <ptr to new allocated object>;
            return SWIG_NEWOBJ;
          } else {
            *ptr = <ptr to old object>;
            return SWIG_OLDOBJ;
          }
        } else {
          return SWIG_BADOBJ;
        }
      }

   Of course, returning the plain '0(success)/-1(fail)' still works, but you can be
   more explicit by returning SWIG_BADOBJ, SWIG_ERROR or any of the
   SWIG errors code.

   Finally, if the SWIG_CASTRANK_MODE is enabled, the result code
   allows to return the 'cast rank', for example, if you have this

       int food(double)
       int fooi(int);

   and you call

      food(1)   // cast rank '1'  (1 -> 1.0)
      fooi(1)   // cast rank '0'

   just use the SWIG_AddCast()/SWIG_CheckState()
*/

#define SWIG_OK                    (0)
#define SWIG_ERROR                 (-1)
#define SWIG_IsOK(r)               (r >= 0)
#define SWIG_ArgError(r)           ((r != SWIG_ERROR) ? r : SWIG_TypeError)

/* The CastRankLimit says how many bits are used for the cast rank */
#define SWIG_CASTRANKLIMIT         (1 << 8)
/* The NewMask denotes the object was created (using new/malloc) */
#define SWIG_NEWOBJMASK            (SWIG_CASTRANKLIMIT  << 1)
/* The TmpMask is for in/out typemaps that use temporal objects */
#define SWIG_TMPOBJMASK            (SWIG_NEWOBJMASK << 1)
/* Simple returning values */
#define SWIG_BADOBJ                (SWIG_ERROR)
#define SWIG_OLDOBJ                (SWIG_OK)
#define SWIG_NEWOBJ                (SWIG_OK | SWIG_NEWOBJMASK)
#define SWIG_TMPOBJ                (SWIG_OK | SWIG_TMPOBJMASK)
/* Check, add and del mask methods */
#define SWIG_AddNewMask(r)         (SWIG_IsOK(r) ? (r | SWIG_NEWOBJMASK) : r)
#define SWIG_DelNewMask(r)         (SWIG_IsOK(r) ? (r & ~SWIG_NEWOBJMASK) : r)
#define SWIG_IsNewObj(r)           (SWIG_IsOK(r) && (r & SWIG_NEWOBJMASK))
#define SWIG_AddTmpMask(r)         (SWIG_IsOK(r) ? (r | SWIG_TMPOBJMASK) : r)
#define SWIG_DelTmpMask(r)         (SWIG_IsOK(r) ? (r & ~SWIG_TMPOBJMASK) : r)
#define SWIG_IsTmpObj(r)           (SWIG_IsOK(r) && (r & SWIG_TMPOBJMASK))

/* Cast-Rank Mode */
#if defined(SWIG_CASTRANK_MODE)
#  ifndef SWIG_TypeRank
#    define SWIG_TypeRank             unsigned long
#  endif
#  ifndef SWIG_MAXCASTRANK            /* Default cast allowed */
#    define SWIG_MAXCASTRANK          (2)
#  endif
#  define SWIG_CASTRANKMASK          ((SWIG_CASTRANKLIMIT) -1)
#  define SWIG_CastRank(r)           (r & SWIG_CASTRANKMASK)
SWIGINTERNINLINE int SWIG_AddCast(int r)
{
    return SWIG_IsOK(r) ? ((SWIG_CastRank(r) < SWIG_MAXCASTRANK) ? (r + 1) : SWIG_ERROR) : r;
}
SWIGINTERNINLINE int SWIG_CheckState(int r)
{
    return SWIG_IsOK(r) ? SWIG_CastRank(r) + 1 : 0;
}
#else /* no cast-rank mode */
#  define SWIG_AddCast(r) (r)
#  define SWIG_CheckState(r) (SWIG_IsOK(r) ? 1 : 0)
#endif


#include <string.h>

#ifdef __cplusplus
extern "C" {
#endif

    typedef void *(*swig_converter_func)(void *, int *);
    typedef struct swig_type_info *(*swig_dycast_func)(void **);

    /* Structure to store information on one type */
    typedef struct swig_type_info
    {
        const char             *name;			/* mangled name of this type */
        const char             *str;			/* human readable name of this type */
        swig_dycast_func        dcast;		/* dynamic cast function down a hierarchy */
        struct swig_cast_info  *cast;			/* linked list of types that can cast into this type */
        void                   *clientdata;		/* language specific type data */
        int                    owndata;		/* flag if the structure owns the clientdata */
    } swig_type_info;

    /* Structure to store a type and conversion function used for casting */
    typedef struct swig_cast_info
    {
        swig_type_info         *type;			/* pointer to type that is equivalent to this type */
        swig_converter_func     converter;		/* function to cast the void pointers */
        struct swig_cast_info  *next;			/* pointer to next cast in linked list */
        struct swig_cast_info  *prev;			/* pointer to the previous cast */
    } swig_cast_info;

    /* Structure used to store module information
     * Each module generates one structure like this, and the runtime collects
     * all of these structures and stores them in a circularly linked list.*/
    typedef struct swig_module_info
    {
        swig_type_info         **types;		/* Array of pointers to swig_type_info structures that are in this module */
        size_t                 size;		        /* Number of types in this module */
        struct swig_module_info *next;		/* Pointer to next element in circularly linked list */
        swig_type_info         **type_initial;	/* Array of initially generated type structures */
        swig_cast_info         **cast_initial;	/* Array of initially generated casting structures */
        void                    *clientdata;		/* Language specific module data */
    } swig_module_info;

    /*
      Compare two type names skipping the space characters, therefore
      "char*" == "char *" and "Class<int>" == "Class<int >", etc.

      Return 0 when the two name types are equivalent, as in
      strncmp, but skipping ' '.
    */
    SWIGRUNTIME int
    SWIG_TypeNameComp(const char *f1, const char *l1,
                      const char *f2, const char *l2)
    {
        for (; (f1 != l1) && (f2 != l2); ++f1, ++f2)
        {
            while ((*f1 == ' ') && (f1 != l1))
            {
                ++f1;
            }
            while ((*f2 == ' ') && (f2 != l2))
            {
                ++f2;
            }
            if (*f1 != *f2)
            {
                return (*f1 > *f2) ? 1 : -1;
            }
        }
        return (int)((l1 - f1) - (l2 - f2));
    }

    /*
      Check type equivalence in a name list like <name1>|<name2>|...
      Return 0 if equal, -1 if nb < tb, 1 if nb > tb
    */
    SWIGRUNTIME int
    SWIG_TypeCmp(const char *nb, const char *tb)
    {
        int equiv = 1;
        const char* te = tb + strlen(tb);
        const char* ne = nb;
        while (equiv != 0 && *ne)
        {
            for (nb = ne; *ne; ++ne)
            {
                if (*ne == '|')
                {
                    break;
                }
            }
            equiv = SWIG_TypeNameComp(nb, ne, tb, te);
            if (*ne)
            {
                ++ne;
            }
        }
        return equiv;
    }

    /*
      Check type equivalence in a name list like <name1>|<name2>|...
      Return 0 if not equal, 1 if equal
    */
    SWIGRUNTIME int
    SWIG_TypeEquiv(const char *nb, const char *tb)
    {
        return SWIG_TypeCmp(nb, tb) == 0 ? 1 : 0;
    }

    /*
      Check the typename
    */
    SWIGRUNTIME swig_cast_info *
    SWIG_TypeCheck(const char *c, swig_type_info *ty)
    {
        if (ty)
        {
            swig_cast_info *iter = ty->cast;
            while (iter)
            {
                if (strcmp(iter->type->name, c) == 0)
                {
                    if (iter == ty->cast)
                    {
                        return iter;
                    }
                    /* Move iter to the top of the linked list */
                    iter->prev->next = iter->next;
                    if (iter->next)
                    {
                        iter->next->prev = iter->prev;
                    }
                    iter->next = ty->cast;
                    iter->prev = 0;
                    if (ty->cast)
                    {
                        ty->cast->prev = iter;
                    }
                    ty->cast = iter;
                    return iter;
                }
                iter = iter->next;
            }
        }
        return 0;
    }

    /*
      Identical to SWIG_TypeCheck, except strcmp is replaced with a pointer comparison
    */
    SWIGRUNTIME swig_cast_info *
    SWIG_TypeCheckStruct(swig_type_info *from, swig_type_info *ty)
    {
        if (ty)
        {
            swig_cast_info *iter = ty->cast;
            while (iter)
            {
                if (iter->type == from)
                {
                    if (iter == ty->cast)
                    {
                        return iter;
                    }
                    /* Move iter to the top of the linked list */
                    iter->prev->next = iter->next;
                    if (iter->next)
                    {
                        iter->next->prev = iter->prev;
                    }
                    iter->next = ty->cast;
                    iter->prev = 0;
                    if (ty->cast)
                    {
                        ty->cast->prev = iter;
                    }
                    ty->cast = iter;
                    return iter;
                }
                iter = iter->next;
            }
        }
        return 0;
    }

    /*
      Cast a pointer up an inheritance hierarchy
    */
    SWIGRUNTIMEINLINE void *
    SWIG_TypeCast(swig_cast_info *ty, void *ptr, int *newmemory)
    {
        return ((!ty) || (!ty->converter)) ? ptr : (*ty->converter)(ptr, newmemory);
    }

    /*
       Dynamic pointer casting. Down an inheritance hierarchy
    */
    SWIGRUNTIME swig_type_info *
    SWIG_TypeDynamicCast(swig_type_info *ty, void **ptr)
    {
        swig_type_info *lastty = ty;
        if (!ty || !ty->dcast)
        {
            return ty;
        }
        while (ty && (ty->dcast))
        {
            ty = (*ty->dcast)(ptr);
            if (ty)
            {
                lastty = ty;
            }
        }
        return lastty;
    }

    /*
      Return the name associated with this type
    */
    SWIGRUNTIMEINLINE const char *
    SWIG_TypeName(const swig_type_info *ty)
    {
        return ty->name;
    }

    /*
      Return the pretty name associated with this type,
      that is an unmangled type name in a form presentable to the user.
    */
    SWIGRUNTIME const char *
    SWIG_TypePrettyName(const swig_type_info *type)
    {
        /* The "str" field contains the equivalent pretty names of the
           type, separated by vertical-bar characters.  We choose
           to print the last name, as it is often (?) the most
           specific. */
        if (!type)
        {
            return NULL;
        }
        if (type->str != NULL)
        {
            const char *last_name = type->str;
            const char *s;
            for (s = type->str; *s; s++)
                if (*s == '|')
                {
                    last_name = s + 1;
                }
            return last_name;
        }
        else
        {
            return type->name;
        }
    }

    /*
       Set the clientdata field for a type
    */
    SWIGRUNTIME void
    SWIG_TypeClientData(swig_type_info *ti, void *clientdata)
    {
        swig_cast_info *cast = ti->cast;
        /* if (ti->clientdata == clientdata) return; */
        ti->clientdata = clientdata;

        while (cast)
        {
            if (!cast->converter)
            {
                swig_type_info *tc = cast->type;
                if (!tc->clientdata)
                {
                    SWIG_TypeClientData(tc, clientdata);
                }
            }
            cast = cast->next;
        }
    }
    SWIGRUNTIME void
    SWIG_TypeNewClientData(swig_type_info *ti, void *clientdata)
    {
        SWIG_TypeClientData(ti, clientdata);
        ti->owndata = 1;
    }

    /*
      Search for a swig_type_info structure only by mangled name
      Search is a O(log #types)

      We start searching at module start, and finish searching when start == end.
      Note: if start == end at the beginning of the function, we go all the way around
      the circular list.
    */
    SWIGRUNTIME swig_type_info *
    SWIG_MangledTypeQueryModule(swig_module_info *start,
                                swig_module_info *end,
                                const char *name)
    {
        swig_module_info *iter = start;
        do
        {
            if (iter->size)
            {
                register size_t l = 0;
                register size_t r = iter->size - 1;
                do
                {
                    /* since l+r >= 0, we can (>> 1) instead (/ 2) */
                    register size_t i = (l + r) >> 1;
                    const char *iname = iter->types[i]->name;
                    if (iname)
                    {
                        register int compare = strcmp(name, iname);
                        if (compare == 0)
                        {
                            return iter->types[i];
                        }
                        else if (compare < 0)
                        {
                            if (i)
                            {
                                r = i - 1;
                            }
                            else
                            {
                                break;
                            }
                        }
                        else if (compare > 0)
                        {
                            l = i + 1;
                        }
                    }
                    else
                    {
                        break; /* should never happen */
                    }
                }
                while (l <= r);
            }
            iter = iter->next;
        }
        while (iter != end);
        return 0;
    }

    /*
      Search for a swig_type_info structure for either a mangled name or a human readable name.
      It first searches the mangled names of the types, which is a O(log #types)
      If a type is not found it then searches the human readable names, which is O(#types).

      We start searching at module start, and finish searching when start == end.
      Note: if start == end at the beginning of the function, we go all the way around
      the circular list.
    */
    SWIGRUNTIME swig_type_info *
    SWIG_TypeQueryModule(swig_module_info *start,
                         swig_module_info *end,
                         const char *name)
    {
        /* STEP 1: Search the name field using binary search */
        swig_type_info *ret = SWIG_MangledTypeQueryModule(start, end, name);
        if (ret)
        {
            return ret;
        }
        else
        {
            /* STEP 2: If the type hasn't been found, do a complete search
               of the str field (the human readable name) */
            swig_module_info *iter = start;
            do
            {
                register size_t i = 0;
                for (; i < iter->size; ++i)
                {
                    if (iter->types[i]->str && (SWIG_TypeEquiv(iter->types[i]->str, name)))
                    {
                        return iter->types[i];
                    }
                }
                iter = iter->next;
            }
            while (iter != end);
        }

        /* neither found a match */
        return 0;
    }

    /*
       Pack binary data into a string
    */
    SWIGRUNTIME char *
    SWIG_PackData(char *c, void *ptr, size_t sz)
    {
        static const char hex[17] = "0123456789abcdef";
        register const unsigned char *u = (unsigned char *) ptr;
        register const unsigned char *eu =  u + sz;
        for (; u != eu; ++u)
        {
            register unsigned char uu = *u;
            *(c++) = hex[(uu & 0xf0) >> 4];
            *(c++) = hex[uu & 0xf];
        }
        return c;
    }

    /*
       Unpack binary data from a string
    */
    SWIGRUNTIME const char *
    SWIG_UnpackData(const char *c, void *ptr, size_t sz)
    {
        register unsigned char *u = (unsigned char *) ptr;
        register const unsigned char *eu = u + sz;
        for (; u != eu; ++u)
        {
            register char d = *(c++);
            register unsigned char uu;
            if ((d >= '0') && (d <= '9'))
            {
                uu = ((d - '0') << 4);
            }
            else if ((d >= 'a') && (d <= 'f'))
            {
                uu = ((d - ('a' - 10)) << 4);
            }
            else
            {
                return (char *) 0;
            }
            d = *(c++);
            if ((d >= '0') && (d <= '9'))
            {
                uu |= (d - '0');
            }
            else if ((d >= 'a') && (d <= 'f'))
            {
                uu |= (d - ('a' - 10));
            }
            else
            {
                return (char *) 0;
            }
            *u = uu;
        }
        return c;
    }

    /*
       Pack 'void *' into a string buffer.
    */
    SWIGRUNTIME char *
    SWIG_PackVoidPtr(char *buff, void *ptr, const char *name, size_t bsz)
    {
        char *r = buff;
        if ((2 * sizeof(void *) + 2) > bsz)
        {
            return 0;
        }
        *(r++) = '_';
        r = SWIG_PackData(r, &ptr, sizeof(void *));
        if (strlen(name) + 1 > (bsz - (r - buff)))
        {
            return 0;
        }
        strcpy(r, name);
        return buff;
    }

    SWIGRUNTIME const char *
    SWIG_UnpackVoidPtr(const char *c, void **ptr, const char *name)
    {
        if (*c != '_')
        {
            if (strcmp(c, "NULL") == 0)
            {
                *ptr = (void *) 0;
                return name;
            }
            else
            {
                return 0;
            }
        }
        return SWIG_UnpackData(++c, ptr, sizeof(void *));
    }

    SWIGRUNTIME char *
    SWIG_PackDataName(char *buff, void *ptr, size_t sz, const char *name, size_t bsz)
    {
        char *r = buff;
        size_t lname = (name ? strlen(name) : 0);
        if ((2 * sz + 2 + lname) > bsz)
        {
            return 0;
        }
        *(r++) = '_';
        r = SWIG_PackData(r, ptr, sz);
        if (lname)
        {
            strncpy(r, name, lname + 1);
        }
        else
        {
            *r = 0;
        }
        return buff;
    }

    SWIGRUNTIME const char *
    SWIG_UnpackDataName(const char *c, void *ptr, size_t sz, const char *name)
    {
        if (*c != '_')
        {
            if (strcmp(c, "NULL") == 0)
            {
                memset(ptr, 0, sz);
                return name;
            }
            else
            {
                return 0;
            }
        }
        return SWIG_UnpackData(++c, ptr, sz);
    }

#ifdef __cplusplus
}
#endif

/*  Errors in SWIG */
#define  SWIG_UnknownError    	   -1
#define  SWIG_IOError        	   -2
#define  SWIG_RuntimeError   	   -3
#define  SWIG_IndexError     	   -4
#define  SWIG_TypeError      	   -5
#define  SWIG_DivisionByZero 	   -6
#define  SWIG_OverflowError  	   -7
#define  SWIG_SyntaxError    	   -8
#define  SWIG_ValueError     	   -9
#define  SWIG_SystemError    	   -10
#define  SWIG_AttributeError 	   -11
#define  SWIG_MemoryError    	   -12
#define  SWIG_NullReferenceError   -13



/* Scilab function name management */
#include <stdlib.h>
static char* fname = NULL;
static char* SWIG_Scilab_GetFname(void)
{
    return fname;
}
static void SWIG_Scilab_SetFname(char* _fname)
{
    if (fname != NULL)
    {
        free(fname);
    }
    fname = strdup(_fname);
}
/* Scilab output argument management */
static int outputPosition = -1;
static int SWIG_Scilab_GetOutputPosition(void)
{
    return outputPosition;
}
static int SWIG_Scilab_GetOutputPositionAndReset(void)
{
    int returnValue = outputPosition;
    outputPosition = -1; /* Set as read */
    return returnValue;
}
static void SWIG_Scilab_SetOutputPosition(int _outputPosition)
{
    outputPosition = _outputPosition;
}

#define Scilab_Error_Occurred() 0
#define SWIG_Scilab_AddErrorMsg(msg) {;}



/* Scilab standard headers */
#ifdef __cplusplus
extern "C" {
#endif
#include "MALLOC.h"
#include "sciprint.h"
#include "Scierror.h"
#include "api_scilab.h"
#include "localization.h"
#include "freeArrayOfString.h"
#ifdef __cplusplus
}
#endif

#undef Max
#undef Min

typedef int SciObject;


/* -----------------------------------------------------------------------------
 * error manipulation
 * ----------------------------------------------------------------------------- */

SWIGINTERN const char*
SWIG_Scilab_ErrorType(int code)
{
    switch (code)
    {
        case SWIG_MemoryError:
            return "MemoryError";
        case SWIG_IOError:
            return "IOError";
        case SWIG_RuntimeError:
            return "RuntimeError";
        case SWIG_IndexError:
            return "IndexError";
        case SWIG_TypeError:
            return "TypeError";
        case SWIG_DivisionByZero:
            return "ZeroDivisionError";
        case SWIG_OverflowError:
            return "OverflowError";
        case SWIG_SyntaxError:
            return "SyntaxError";
        case SWIG_ValueError:
            return "ValueError";
        case SWIG_SystemError:
            return "SystemError";
        case SWIG_AttributeError:
            return "AttributeError";
        default:
            return "RuntimeError";
    }
}

SWIGINTERN void
SWIG_Scilab_ErrorMsg(int code, const char *mesg)
{
    sciprint(_("SWIG/Scilab Error : %s\n%s"), SWIG_Scilab_ErrorType(code), mesg);
}

#define SCILAB_VERSION_54_OR_HIGHER (SCI_VERSION_MAJOR > 5) || ((SCI_VERSION_MAJOR == 5) && (SCI_VERSION_MINOR >= 4))
#if !SCILAB_VERSION_54_OR_HIGHER
#include "stack-c.h"
#endif

#define SWIG_fail                 return SWIG_ERROR;
#define SWIG_ErrorType(code)      SWIG_Scilab_ErrorType(code)
#define SWIG_Error(code, msg)     SWIG_Scilab_ErrorMsg(code,msg)

/* Used for C++ enums */
//#define SWIG_AsVal_int(scilabValue, valuePointer) SWIG_SciDouble_AsInt(pvApiCtx, scilabValue, valuePointer, fname)

#if SCILAB_VERSION_54_OR_HIGHER
#define SWIG_CheckInputArgument(pvApiCtx, minInputArgument, maxInputArgument) CheckInputArgument(pvApiCtx, minInputArgument, maxInputArgument)
#define SWIG_CheckOutputArgument(pvApiCtx, minOutputArgument, maxOutputArgument) CheckOutputArgument(pvApiCtx, minOutputArgument, maxOutputArgument)
#define SWIG_NbInputArgument(pvApiCtx) nbInputArgument(pvApiCtx)

#else

#define SWIG_CheckInputArgument(pvApiCtx, minInputArgument, maxInputArgument) CheckRhs(minInputArgument, maxInputArgument)
#define SWIG_CheckOutputArgument(pvApiCtx, minOutputArgument, maxOutputArgument) CheckLhs(minOutputArgument, maxOutputArgument)
#define SWIG_NbInputArgument(pvApiCtx) Rhs
#endif


SWIGINTERN int
SwigScilabPtrToObject(void *_pvApiCtx, int _iVar, void **_pObjValue, swig_type_info *_descriptor, int _flags, char *_fname)
{
    SciErr sciErr;
    int iType = 0;
    int *piAddrVar = NULL;

    sciErr = getVarAddressFromPosition(_pvApiCtx, _iVar, &piAddrVar);
    if (sciErr.iErr)
    {
        printError(&sciErr, 0);
        return SWIG_ERROR;
    }

    sciErr = getVarType(_pvApiCtx, piAddrVar, &iType);
    if (sciErr.iErr)
    {
        printError(&sciErr, 0);
        return SWIG_ERROR;
    }
    if (iType != sci_pointer)
    {
        //Scierror(999, _("%s: Wrong type for input argument #%d: A pointer expected.\n"), _fname, _iVar);
        return SWIG_ERROR;
    }

    sciErr = getPointer(_pvApiCtx, piAddrVar, _pObjValue);
    if (sciErr.iErr)
    {
        printError(&sciErr, 0);
        return SWIG_ERROR;
    }

    return SWIG_OK;
}

SWIGRUNTIMEINLINE int
SwigScilabPtrFromObject(void *_pvApiCtx, int _iVarOut, void *_object, swig_type_info *_descriptor, int _flags)
{
    SciErr sciErr;

    sciErr = createPointer(pvApiCtx, Rhs + _iVarOut, (void *)_object);
    if (sciErr.iErr)
    {
        printError(&sciErr, 0);
        return SWIG_ERROR;
    }

    return Rhs + _iVarOut;
}

SWIGRUNTIME int
SWIG_Scilab_ConvertPacked(void *_pvApiCtx, int _iVar, void *_ptr, int sz, swig_type_info *ty, char *_fname)
{
    swig_cast_info *tc;

    SciErr sciErr;
    int iRows = 0;
    int iCols = 0;
    int iType = 0;
    int *piAddrVar = NULL;
    char *pstStrings = NULL;
    int piLength = 0;

    sciErr = getVarAddressFromPosition(pvApiCtx, _iVar, &piAddrVar);
    if (sciErr.iErr)
    {
        printError(&sciErr, 0);
        return SWIG_ERROR;
    }

    sciErr = getVarType(pvApiCtx, piAddrVar, &iType);
    if (sciErr.iErr)
    {
        printError(&sciErr, 0);
        return SWIG_ERROR;
    }
    if (iType != sci_strings)
    {
        Scierror(999, _("%s: Wrong type for input argument #%d: A string expected.\n"), _fname, _iVar);
        return SWIG_ERROR;
    }

    sciErr = getMatrixOfString(pvApiCtx, piAddrVar, &iRows, &iCols, &piLength, NULL);
    if (sciErr.iErr)
    {
        printError(&sciErr, 0);
        return SWIG_ERROR;
    }
    if (iRows * iCols != 1)
    {
        Scierror(999, _("%s: Wrong size for input argument #%d: A string expected.\n"), _fname, _iVar);
        return SWIG_ERROR;
    }

    pstStrings = (char *)MALLOC(sizeof(char) * (piLength + 1));
    sciErr = getMatrixOfString(pvApiCtx, piAddrVar, &iRows, &iCols, &piLength, (char **)&pstStrings);
    if (sciErr.iErr)
    {
        printError(&sciErr, 0);
        return SWIG_ERROR;
    }

    /* Pointer values must start with leading underscore */
    if (*pstStrings != '_')
    {
        return SWIG_ERROR;
    }
    pstStrings++;
    pstStrings = (char*)SWIG_UnpackData(pstStrings, _ptr, sz);
    if (ty)
    {
        tc = SWIG_TypeCheck(pstStrings, ty);
        if (!tc)
        {
            return SWIG_ERROR;
        }
    }
    FREE(pstStrings);
    return SWIG_OK;
}

SWIGRUNTIME int
SWIG_Scilab_NewMemberObj(void *_pvApiCtx, int _iVarOut, void *_ptr, int _sz, swig_type_info *_type)
{
    char result[1024];
    char *r = result;

    SciErr sciErr;
    char **pstData = NULL;
    if ((2 * _sz + 1 + strlen(_type->name)) > 1000)
    {
        return SWIG_ERROR;
    }
    *(r++) = '_';
    r = SWIG_PackData(r, _ptr, _sz);
    strcpy(r, _type->name);

    pstData = (char **)malloc(sizeof(char *));
    pstData[0] = strdup(r);

    sciErr = createMatrixOfString(_pvApiCtx, Rhs + _iVarOut, 1, 1, (char **)pstData);
    if (sciErr.iErr)
    {
        printError(&sciErr, 0);
        return SWIG_ERROR;
    }

    free(pstData[0]);

    return Rhs + _iVarOut;
}

SWIGRUNTIME int
SWIG_Scilab_SetOutput(void *_pvApiCtx, SciObject _output)
{
    int outputPosition = SWIG_Scilab_GetOutputPositionAndReset();
    if (outputPosition < 0 || _output < 0)
    {
        return SWIG_ERROR;
    }
#if SCILAB_VERSION_54_OR_HIGHER
    AssignOutputVariable(pvApiCtx, outputPosition) = _output;
#else
    LhsVar(outputPosition) = _output;
#endif
    return SWIG_OK;
}

#define SWIG_Scilab_Raise(obj, type, desc) SwigScilabRaise(type)

SWIGRUNTIME int
SwigScilabRaise(const char *type)
{
    Scierror(999, "An exception of type %s has been thrown.\n", type);
#ifdef __cplusplus
    throw;
#endif
}




#define SWIG_exception_fail(code, msg) do { SWIG_Error(code, msg); SWIG_fail; } while(0)

#define SWIG_contract_assert(expr, msg) if (!(expr)) { SWIG_Error(SWIG_RuntimeError, msg); SWIG_fail; } else



/* -------- TYPES TABLE (BEGIN) -------- */

#define SWIGTYPE_p_MPI_Op swig_types[0]
#define SWIGTYPE_p_char swig_types[1]
static swig_type_info *swig_types[3];
static swig_module_info swig_module = {swig_types, 2, 0, 0, 0, 0};
#define SWIG_TypeQuery(name) SWIG_TypeQueryModule(&swig_module, &swig_module, name)
#define SWIG_MangledTypeQuery(name) SWIG_MangledTypeQueryModule(&swig_module, &swig_module, name)

/* -------- TYPES TABLE (END) -------- */


#define SWIGVERSION 0x020011
#define SWIG_VERSION SWIGVERSION


#define SWIG_as_voidptr(a) (void *)((const void *)(a))
#define SWIG_as_voidptrptr(a) ((void)SWIG_as_voidptr(*a),(void**)(a))


#include <mpi.h>



MPI_Op MPI_Max()
{
    return MPI_MAX;
}
MPI_Op MPI_Min()
{
    return MPI_MIN;
}
MPI_Op MPI_Sum()
{
    return MPI_SUM;
}
MPI_Op MPI_Prod()
{
    return MPI_PROD;
}
MPI_Op MPI_Land()
{
    return MPI_LAND;
}
MPI_Op MPI_Band()
{
    return MPI_BAND;
}
MPI_Op MPI_Lor()
{
    return MPI_LOR;
}
MPI_Op MPI_Bor()
{
    return MPI_BOR;
}
MPI_Op MPI_LXor()
{
    return MPI_LXOR;
}
MPI_Op MPI_BXor()
{
    return MPI_BXOR;
}
MPI_Op MPI_MaxLoc()
{
    return MPI_MAXLOC;
}
MPI_Op MPI_MinLoc()
{
    return MPI_MINLOC;
}
MPI_Op MPI_Replace()
{
    return MPI_REPLACE;
}


int _wrap_MPI_Max(char *fname, unsigned long fname_len)
{
    MPI_Op result;

    SWIG_CheckInputArgument(pvApiCtx, 0, 0);
    SWIG_CheckOutputArgument(pvApiCtx, 1, 1);
    SWIG_Scilab_SetFname(fname);
    result = MPI_Max();
    SWIG_Scilab_SetOutputPosition(1); /* functionReturnTypemap */
    if (!SWIG_IsOK(SWIG_Scilab_SetOutput(pvApiCtx, SwigScilabPtrFromObject(pvApiCtx, SWIG_Scilab_GetOutputPosition(), (MPI_Op *)memcpy((MPI_Op *)malloc(sizeof(MPI_Op)), &result, sizeof(MPI_Op)), SWIGTYPE_p_MPI_Op, SWIG_POINTER_OWN |  0 ))))
    {
        return SWIG_ERROR;
    }
    return SWIG_OK;
}


int _wrap_MPI_Min(char *fname, unsigned long fname_len)
{
    MPI_Op result;

    SWIG_CheckInputArgument(pvApiCtx, 0, 0);
    SWIG_CheckOutputArgument(pvApiCtx, 1, 1);
    SWIG_Scilab_SetFname(fname);
    result = MPI_Min();
    SWIG_Scilab_SetOutputPosition(1); /* functionReturnTypemap */
    if (!SWIG_IsOK(SWIG_Scilab_SetOutput(pvApiCtx, SwigScilabPtrFromObject(pvApiCtx, SWIG_Scilab_GetOutputPosition(), (MPI_Op *)memcpy((MPI_Op *)malloc(sizeof(MPI_Op)), &result, sizeof(MPI_Op)), SWIGTYPE_p_MPI_Op, SWIG_POINTER_OWN |  0 ))))
    {
        return SWIG_ERROR;
    }
    return SWIG_OK;
}


int _wrap_MPI_Sum(char *fname, unsigned long fname_len)
{
    MPI_Op result;

    SWIG_CheckInputArgument(pvApiCtx, 0, 0);
    SWIG_CheckOutputArgument(pvApiCtx, 1, 1);
    SWIG_Scilab_SetFname(fname);
    result = MPI_Sum();
    SWIG_Scilab_SetOutputPosition(1); /* functionReturnTypemap */
    if (!SWIG_IsOK(SWIG_Scilab_SetOutput(pvApiCtx, SwigScilabPtrFromObject(pvApiCtx, SWIG_Scilab_GetOutputPosition(), (MPI_Op *)memcpy((MPI_Op *)malloc(sizeof(MPI_Op)), &result, sizeof(MPI_Op)), SWIGTYPE_p_MPI_Op, SWIG_POINTER_OWN |  0 ))))
    {
        return SWIG_ERROR;
    }
    return SWIG_OK;
}


int _wrap_MPI_Prod(char *fname, unsigned long fname_len)
{
    MPI_Op result;

    SWIG_CheckInputArgument(pvApiCtx, 0, 0);
    SWIG_CheckOutputArgument(pvApiCtx, 1, 1);
    SWIG_Scilab_SetFname(fname);
    result = MPI_Prod();
    SWIG_Scilab_SetOutputPosition(1); /* functionReturnTypemap */
    if (!SWIG_IsOK(SWIG_Scilab_SetOutput(pvApiCtx, SwigScilabPtrFromObject(pvApiCtx, SWIG_Scilab_GetOutputPosition(), (MPI_Op *)memcpy((MPI_Op *)malloc(sizeof(MPI_Op)), &result, sizeof(MPI_Op)), SWIGTYPE_p_MPI_Op, SWIG_POINTER_OWN |  0 ))))
    {
        return SWIG_ERROR;
    }
    return SWIG_OK;
}


int _wrap_MPI_Land(char *fname, unsigned long fname_len)
{
    MPI_Op result;

    SWIG_CheckInputArgument(pvApiCtx, 0, 0);
    SWIG_CheckOutputArgument(pvApiCtx, 1, 1);
    SWIG_Scilab_SetFname(fname);
    result = MPI_Land();
    SWIG_Scilab_SetOutputPosition(1); /* functionReturnTypemap */
    if (!SWIG_IsOK(SWIG_Scilab_SetOutput(pvApiCtx, SwigScilabPtrFromObject(pvApiCtx, SWIG_Scilab_GetOutputPosition(), (MPI_Op *)memcpy((MPI_Op *)malloc(sizeof(MPI_Op)), &result, sizeof(MPI_Op)), SWIGTYPE_p_MPI_Op, SWIG_POINTER_OWN |  0 ))))
    {
        return SWIG_ERROR;
    }
    return SWIG_OK;
}


int _wrap_MPI_Band(char *fname, unsigned long fname_len)
{
    MPI_Op result;

    SWIG_CheckInputArgument(pvApiCtx, 0, 0);
    SWIG_CheckOutputArgument(pvApiCtx, 1, 1);
    SWIG_Scilab_SetFname(fname);
    result = MPI_Band();
    SWIG_Scilab_SetOutputPosition(1); /* functionReturnTypemap */
    if (!SWIG_IsOK(SWIG_Scilab_SetOutput(pvApiCtx, SwigScilabPtrFromObject(pvApiCtx, SWIG_Scilab_GetOutputPosition(), (MPI_Op *)memcpy((MPI_Op *)malloc(sizeof(MPI_Op)), &result, sizeof(MPI_Op)), SWIGTYPE_p_MPI_Op, SWIG_POINTER_OWN |  0 ))))
    {
        return SWIG_ERROR;
    }
    return SWIG_OK;
}


int _wrap_MPI_Lor(char *fname, unsigned long fname_len)
{
    MPI_Op result;

    SWIG_CheckInputArgument(pvApiCtx, 0, 0);
    SWIG_CheckOutputArgument(pvApiCtx, 1, 1);
    SWIG_Scilab_SetFname(fname);
    result = MPI_Lor();
    SWIG_Scilab_SetOutputPosition(1); /* functionReturnTypemap */
    if (!SWIG_IsOK(SWIG_Scilab_SetOutput(pvApiCtx, SwigScilabPtrFromObject(pvApiCtx, SWIG_Scilab_GetOutputPosition(), (MPI_Op *)memcpy((MPI_Op *)malloc(sizeof(MPI_Op)), &result, sizeof(MPI_Op)), SWIGTYPE_p_MPI_Op, SWIG_POINTER_OWN |  0 ))))
    {
        return SWIG_ERROR;
    }
    return SWIG_OK;
}


int _wrap_MPI_Bor(char *fname, unsigned long fname_len)
{
    MPI_Op result;

    SWIG_CheckInputArgument(pvApiCtx, 0, 0);
    SWIG_CheckOutputArgument(pvApiCtx, 1, 1);
    SWIG_Scilab_SetFname(fname);
    result = MPI_Bor();
    SWIG_Scilab_SetOutputPosition(1); /* functionReturnTypemap */
    if (!SWIG_IsOK(SWIG_Scilab_SetOutput(pvApiCtx, SwigScilabPtrFromObject(pvApiCtx, SWIG_Scilab_GetOutputPosition(), (MPI_Op *)memcpy((MPI_Op *)malloc(sizeof(MPI_Op)), &result, sizeof(MPI_Op)), SWIGTYPE_p_MPI_Op, SWIG_POINTER_OWN |  0 ))))
    {
        return SWIG_ERROR;
    }
    return SWIG_OK;
}


int _wrap_MPI_LXor(char *fname, unsigned long fname_len)
{
    MPI_Op result;

    SWIG_CheckInputArgument(pvApiCtx, 0, 0);
    SWIG_CheckOutputArgument(pvApiCtx, 1, 1);
    SWIG_Scilab_SetFname(fname);
    result = MPI_LXor();
    SWIG_Scilab_SetOutputPosition(1); /* functionReturnTypemap */
    if (!SWIG_IsOK(SWIG_Scilab_SetOutput(pvApiCtx, SwigScilabPtrFromObject(pvApiCtx, SWIG_Scilab_GetOutputPosition(), (MPI_Op *)memcpy((MPI_Op *)malloc(sizeof(MPI_Op)), &result, sizeof(MPI_Op)), SWIGTYPE_p_MPI_Op, SWIG_POINTER_OWN |  0 ))))
    {
        return SWIG_ERROR;
    }
    return SWIG_OK;
}


int _wrap_MPI_BXor(char *fname, unsigned long fname_len)
{
    MPI_Op result;

    SWIG_CheckInputArgument(pvApiCtx, 0, 0);
    SWIG_CheckOutputArgument(pvApiCtx, 1, 1);
    SWIG_Scilab_SetFname(fname);
    result = MPI_BXor();
    SWIG_Scilab_SetOutputPosition(1); /* functionReturnTypemap */
    if (!SWIG_IsOK(SWIG_Scilab_SetOutput(pvApiCtx, SwigScilabPtrFromObject(pvApiCtx, SWIG_Scilab_GetOutputPosition(), (MPI_Op *)memcpy((MPI_Op *)malloc(sizeof(MPI_Op)), &result, sizeof(MPI_Op)), SWIGTYPE_p_MPI_Op, SWIG_POINTER_OWN |  0 ))))
    {
        return SWIG_ERROR;
    }
    return SWIG_OK;
}


int _wrap_MPI_MaxLoc(char *fname, unsigned long fname_len)
{
    MPI_Op result;

    SWIG_CheckInputArgument(pvApiCtx, 0, 0);
    SWIG_CheckOutputArgument(pvApiCtx, 1, 1);
    SWIG_Scilab_SetFname(fname);
    result = MPI_MaxLoc();
    SWIG_Scilab_SetOutputPosition(1); /* functionReturnTypemap */
    if (!SWIG_IsOK(SWIG_Scilab_SetOutput(pvApiCtx, SwigScilabPtrFromObject(pvApiCtx, SWIG_Scilab_GetOutputPosition(), (MPI_Op *)memcpy((MPI_Op *)malloc(sizeof(MPI_Op)), &result, sizeof(MPI_Op)), SWIGTYPE_p_MPI_Op, SWIG_POINTER_OWN |  0 ))))
    {
        return SWIG_ERROR;
    }
    return SWIG_OK;
}


int _wrap_MPI_MinLoc(char *fname, unsigned long fname_len)
{
    MPI_Op result;

    SWIG_CheckInputArgument(pvApiCtx, 0, 0);
    SWIG_CheckOutputArgument(pvApiCtx, 1, 1);
    SWIG_Scilab_SetFname(fname);
    result = MPI_MinLoc();
    SWIG_Scilab_SetOutputPosition(1); /* functionReturnTypemap */
    if (!SWIG_IsOK(SWIG_Scilab_SetOutput(pvApiCtx, SwigScilabPtrFromObject(pvApiCtx, SWIG_Scilab_GetOutputPosition(), (MPI_Op *)memcpy((MPI_Op *)malloc(sizeof(MPI_Op)), &result, sizeof(MPI_Op)), SWIGTYPE_p_MPI_Op, SWIG_POINTER_OWN |  0 ))))
    {
        return SWIG_ERROR;
    }
    return SWIG_OK;
}


int _wrap_MPI_Replace(char *fname, unsigned long fname_len)
{
    MPI_Op result;

    SWIG_CheckInputArgument(pvApiCtx, 0, 0);
    SWIG_CheckOutputArgument(pvApiCtx, 1, 1);
    SWIG_Scilab_SetFname(fname);
    result = MPI_Replace();
    SWIG_Scilab_SetOutputPosition(1); /* functionReturnTypemap */
    if (!SWIG_IsOK(SWIG_Scilab_SetOutput(pvApiCtx, SwigScilabPtrFromObject(pvApiCtx, SWIG_Scilab_GetOutputPosition(), (MPI_Op *)memcpy((MPI_Op *)malloc(sizeof(MPI_Op)), &result, sizeof(MPI_Op)), SWIGTYPE_p_MPI_Op, SWIG_POINTER_OWN |  0 ))))
    {
        return SWIG_ERROR;
    }
    return SWIG_OK;
}



/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (BEGIN) -------- */

static swig_type_info _swigt__p_MPI_Op = {"_p_MPI_Op", "MPI_Op *", 0, 0, (void*)0, 0};
static swig_type_info _swigt__p_char = {"_p_char", "char *", 0, 0, (void*)0, 0};

static swig_type_info *swig_type_initial[] =
{
    &_swigt__p_MPI_Op,
    &_swigt__p_char,
};

static swig_cast_info _swigc__p_MPI_Op[] = {  {&_swigt__p_MPI_Op, 0, 0, 0}, {0, 0, 0, 0}};
static swig_cast_info _swigc__p_char[] = {  {&_swigt__p_char, 0, 0, 0}, {0, 0, 0, 0}};

static swig_cast_info *swig_cast_initial[] =
{
    _swigc__p_MPI_Op,
    _swigc__p_char,
};


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (END) -------- */

int SWIG_CreateScilabVariables()
{
    return SWIG_OK;
}

#define SWIG_GetModule(clientdata) SWIG_Scilab_GetModule()
#define SWIG_SetModule(clientdata, pointer) SWIG_Scilab_SetModule(pointer)

SWIGRUNTIME swig_module_info*
SWIG_Scilab_GetModule(void)
{
    return NULL;
}

SWIGRUNTIME void
SWIG_Scilab_SetModule(swig_module_info *swig_module)
{

}

/* -----------------------------------------------------------------------------
 * Type initialization:
 * This problem is tough by the requirement that no dynamic
 * memory is used. Also, since swig_type_info structures store pointers to
 * swig_cast_info structures and swig_cast_info structures store pointers back
 * to swig_type_info structures, we need some lookup code at initialization.
 * The idea is that swig generates all the structures that are needed.
 * The runtime then collects these partially filled structures.
 * The SWIG_InitializeModule function takes these initial arrays out of
 * swig_module, and does all the lookup, filling in the swig_module.types
 * array with the correct data and linking the correct swig_cast_info
 * structures together.
 *
 * The generated swig_type_info structures are assigned staticly to an initial
 * array. We just loop through that array, and handle each type individually.
 * First we lookup if this type has been already loaded, and if so, use the
 * loaded structure instead of the generated one. Then we have to fill in the
 * cast linked list. The cast data is initially stored in something like a
 * two-dimensional array. Each row corresponds to a type (there are the same
 * number of rows as there are in the swig_type_initial array). Each entry in
 * a column is one of the swig_cast_info structures for that type.
 * The cast_initial array is actually an array of arrays, because each row has
 * a variable number of columns. So to actually build the cast linked list,
 * we find the array of casts associated with the type, and loop through it
 * adding the casts to the list. The one last trick we need to do is making
 * sure the type pointer in the swig_cast_info struct is correct.
 *
 * First off, we lookup the cast->type name to see if it is already loaded.
 * There are three cases to handle:
 *  1) If the cast->type has already been loaded AND the type we are adding
 *     casting info to has not been loaded (it is in this module), THEN we
 *     replace the cast->type pointer with the type pointer that has already
 *     been loaded.
 *  2) If BOTH types (the one we are adding casting info to, and the
 *     cast->type) are loaded, THEN the cast info has already been loaded by
 *     the previous module so we just ignore it.
 *  3) Finally, if cast->type has not already been loaded, then we add that
 *     swig_cast_info to the linked list (because the cast->type) pointer will
 *     be correct.
 * ----------------------------------------------------------------------------- */

#ifdef __cplusplus
extern "C" {
#if 0
} /* c-mode */
#endif
#endif

#if 0
#define SWIGRUNTIME_DEBUG
#endif


SWIGRUNTIME void
SWIG_InitializeModule(void *clientdata)
{
    size_t i;
    swig_module_info *module_head, *iter;
    int found, init;

    /* check to see if the circular list has been setup, if not, set it up */
    if (swig_module.next == 0)
    {
        /* Initialize the swig_module */
        swig_module.type_initial = swig_type_initial;
        swig_module.cast_initial = swig_cast_initial;
        swig_module.next = &swig_module;
        init = 1;
    }
    else
    {
        init = 0;
    }

    /* Try and load any already created modules */
    module_head = SWIG_GetModule(clientdata);
    if (!module_head)
    {
        /* This is the first module loaded for this interpreter */
        /* so set the swig module into the interpreter */
        SWIG_SetModule(clientdata, &swig_module);
        module_head = &swig_module;
    }
    else
    {
        /* the interpreter has loaded a SWIG module, but has it loaded this one? */
        found = 0;
        iter = module_head;
        do
        {
            if (iter == &swig_module)
            {
                found = 1;
                break;
            }
            iter = iter->next;
        }
        while (iter != module_head);

        /* if the is found in the list, then all is done and we may leave */
        if (found)
        {
            return;
        }
        /* otherwise we must add out module into the list */
        swig_module.next = module_head->next;
        module_head->next = &swig_module;
    }

    /* When multiple interpeters are used, a module could have already been initialized in
         a different interpreter, but not yet have a pointer in this interpreter.
         In this case, we do not want to continue adding types... everything should be
         set up already */
    if (init == 0)
    {
        return;
    }

    /* Now work on filling in swig_module.types */
#ifdef SWIGRUNTIME_DEBUG
    printf("SWIG_InitializeModule: size %d\n", swig_module.size);
#endif
    for (i = 0; i < swig_module.size; ++i)
    {
        swig_type_info *type = 0;
        swig_type_info *ret;
        swig_cast_info *cast;

#ifdef SWIGRUNTIME_DEBUG
        printf("SWIG_InitializeModule: type %d %s\n", i, swig_module.type_initial[i]->name);
#endif

        /* if there is another module already loaded */
        if (swig_module.next != &swig_module)
        {
            type = SWIG_MangledTypeQueryModule(swig_module.next, &swig_module, swig_module.type_initial[i]->name);
        }
        if (type)
        {
            /* Overwrite clientdata field */
#ifdef SWIGRUNTIME_DEBUG
            printf("SWIG_InitializeModule: found type %s\n", type->name);
#endif
            if (swig_module.type_initial[i]->clientdata)
            {
                type->clientdata = swig_module.type_initial[i]->clientdata;
#ifdef SWIGRUNTIME_DEBUG
                printf("SWIG_InitializeModule: found and overwrite type %s \n", type->name);
#endif
            }
        }
        else
        {
            type = swig_module.type_initial[i];
        }

        /* Insert casting types */
        cast = swig_module.cast_initial[i];
        while (cast->type)
        {
            /* Don't need to add information already in the list */
            ret = 0;
#ifdef SWIGRUNTIME_DEBUG
            printf("SWIG_InitializeModule: look cast %s\n", cast->type->name);
#endif
            if (swig_module.next != &swig_module)
            {
                ret = SWIG_MangledTypeQueryModule(swig_module.next, &swig_module, cast->type->name);
#ifdef SWIGRUNTIME_DEBUG
                if (ret)
                {
                    printf("SWIG_InitializeModule: found cast %s\n", ret->name);
                }
#endif
            }
            if (ret)
            {
                if (type == swig_module.type_initial[i])
                {
#ifdef SWIGRUNTIME_DEBUG
                    printf("SWIG_InitializeModule: skip old type %s\n", ret->name);
#endif
                    cast->type = ret;
                    ret = 0;
                }
                else
                {
                    /* Check for casting already in the list */
                    swig_cast_info *ocast = SWIG_TypeCheck(ret->name, type);
#ifdef SWIGRUNTIME_DEBUG
                    if (ocast)
                    {
                        printf("SWIG_InitializeModule: skip old cast %s\n", ret->name);
                    }
#endif
                    if (!ocast)
                    {
                        ret = 0;
                    }
                }
            }

            if (!ret)
            {
#ifdef SWIGRUNTIME_DEBUG
                printf("SWIG_InitializeModule: adding cast %s\n", cast->type->name);
#endif
                if (type->cast)
                {
                    type->cast->prev = cast;
                    cast->next = type->cast;
                }
                type->cast = cast;
            }
            cast++;
        }
        /* Set entry in modules->types array equal to the type */
        swig_module.types[i] = type;
    }
    swig_module.types[i] = 0;

#ifdef SWIGRUNTIME_DEBUG
    printf("**** SWIG_InitializeModule: Cast List ******\n");
    for (i = 0; i < swig_module.size; ++i)
    {
        int j = 0;
        swig_cast_info *cast = swig_module.cast_initial[i];
        printf("SWIG_InitializeModule: type %d %s\n", i, swig_module.type_initial[i]->name);
        while (cast->type)
        {
            printf("SWIG_InitializeModule: cast type %s\n", cast->type->name);
            cast++;
            ++j;
        }
        printf("---- Total casts: %d\n", j);
    }
    printf("**** SWIG_InitializeModule: Cast List ******\n");
#endif
}

/* This function will propagate the clientdata field of type to
* any new swig_type_info structures that have been added into the list
* of equivalent types.  It is like calling
* SWIG_TypeClientData(type, clientdata) a second time.
*/
SWIGRUNTIME void
SWIG_PropagateClientData(void)
{
    size_t i;
    swig_cast_info *equiv;
    static int init_run = 0;

    if (init_run)
    {
        return;
    }
    init_run = 1;

    for (i = 0; i < swig_module.size; i++)
    {
        if (swig_module.types[i]->clientdata)
        {
            equiv = swig_module.types[i]->cast;
            while (equiv)
            {
                if (!equiv->converter)
                {
                    if (equiv->type && !equiv->type->clientdata)
                    {
                        SWIG_TypeClientData(equiv->type, swig_module.types[i]->clientdata);
                    }
                }
                equiv = equiv->next;
            }
        }
    }
}

#ifdef __cplusplus
#if 0
{
    /* c-mode */
#endif
}
#endif


#ifdef __cplusplus
extern "C"
#endif
int SWIG_Init(char *fname, unsigned long fname_len)
{
    SWIG_InitializeModule(NULL);
    SWIG_CreateScilabVariables();

    return 0;
}

