// This file is released under the 3-clause BSD license. See COPYING-BSD.
// Generated by builder.sce : Please, do not edit this file
// ----------------------------------------------------------------------------
//
libtestHandler_c_path = get_absolute_file_path('loader.sce');
//
// ulink previous function with same name
[bOK, ilib] = c_link('libtestHandler_c');
if bOK then
  ulink(ilib);
end
//
link('/home/calixte/git/tmp/scilab/scilab/modules/types/.libs/libscitypes' + getdynlibext());
list_functions = [ 'testHandler';
];
addinter(libtestHandler_c_path + filesep() + 'libtestHandler_c' + getdynlibext(), 'libtestHandler_c', list_functions);
// remove temp. variables on stack
clear libtestHandler_c_path;
clear bOK;
clear ilib;
clear list_functions;
// ----------------------------------------------------------------------------
