            Changes between version 5.4.X and 6.0.0 of Scilab
            =================================================


File input/output:
==================

* Cannot use the console I/O with functions : mclose, meof, mget, mgetl, mgetstr, mput, mputl, mputstr, mseek and mtell.

Removed functions (previously declared as obsolete):
====================================================

* maxfile function is now obsolete.

