                     Changes between version 5.5.1 and 5.6.0
                     =======================================

New Features
=============

* New special functions:
 - contour3d - A 3d iso surface plot (see SEP #132)
 - implicitplot3d - A 3d implicit function plot (see SEP #132)

Obsolete & Removed Functions
============================


Scilab Bug Fixes
================


Xcos Bug Fixes
==============


Known issues
=============


